language: python

python: 3.6

stages:
  - test
  - build

before_install:
  - pip install codecov

install:
  - pip install .

script:
  - python setup.py test

after_success:
  - codecov

jobs:
  include:
    - stage: test
    - name: "lint"
      script:
        - python setup.py lint || exit $(($? & 35))
    - python: 3.7
      dist: xenial
    - stage: build
      name: "sdist"
      script:
        - python setup.py sdist
    - name: "bdist_wheel"
      install:
        - pip install . wheel
      script:
        - python setup.py bdist_wheel
    - name: "sphinx docs"
        install:
          - pip install .["docs"]
        script:
          - sphinx-build docs/ build/